# Generated by Django 4.2.7 on 2023-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="fileDir",
            field=models.FileField(null=True, upload_to="files/"),
        ),
    ]
