# Generated by Django 4.2.7 on 2023-11-14 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sharing_app.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sharing_app", "0002_file_filedir"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="fileHash",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="fileType",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="fileDir",
            field=models.FileField(
                null=True, upload_to=sharing_app.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="sender",
            field=models.ForeignKey(
                default=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sharedFiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
