# Generated by Django 4.2.7 on 2023-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing_app", "0003_file_filehash_file_filetype_alter_file_filedir_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="fileHash",
            field=models.CharField(max_length=64),
        ),
    ]
